### ISSUE TITLE
Installing via npm installs all the dev dependencies

### ISSUE THREAD

**Issue by oldskool73** [8bitDesigner/ng-form-group#10]
I just want to use in my project (using webpack), so ran 

`npm i -D ng-form-group`

...but instead of just the source & built files I also got karma and phantom and gulp and all kinds of other stuff installed under `node_modules` in the package.

I think this is because all the dev requirements are listed under `dependencies` in the `package.json`, instead of `devDependencies` where they should be.

**Comment by 8bitDesigner** [comment]
Good catch! We'd been using Bower internally, so we never ran into this before, but now that we're moving our dependency management into NPM, we're going to hit this bug too.

Can you check out v1.4.0 which includes [this fix](https://github.com/8bitDesigner/ng-form-group/pull/11/files) to rejigger the module's declared dependencies?

**Comment by oldskool73** [comment]
Looks good here! 👍

**Comment by 8bitDesigner** [comment]
Perfect, thanks!
