### ISSUE TITLE
Label turns green when there is no form-control class

### ISSUE THREAD

**Issue by aronmgv** [8bitDesigner/ng-form-group#4]
Hey,

I would like to report issue.
All labels within form-group turns green where there is no form-control class within form-group.

Since in one form-group I have 2 fields - to have them in single row they need to be in single form-group -> I cannot use `form-group-without-feedback` since it affects other field..

Example:

``` html
<div class="row">
    <div class="form-group has-feedback">
        <label class="col-md-2 control-label">Deployed:</label>
        <div class="col-md-2 checkbox">
            <label>
                <input type="checkbox" name="deployed" ng-model="networkElement.deployed">
            </label>
        </div>
        <div>
            <label class="col-md-2 control-label">Listening Ports:</label>
            <div class="col-md-5">
                <!--<input type="text" name="listeningPorts" ng-model="networkElement.listeningPorts" class="form-control" placeholder="ports...">-->
                <tags-input min-length="2" name="listeningPorts" ng-model="networkElement.listeningPorts" class="bootstrap" ng-class="onScriptUpdateCss"></tags-input>
            </div>
        </div>
    </div>
</div>
```

This results into both labels to be explicitly green (there is no form-control class).

However I want to validate checkbox if checked.. and place checkmark there.. which wont work if I put there `form-group-without-feedback`

Is it possible to address this behavior? (I TS it a bit and found out it turns all labels green (dunno why) and then it resets everything which has form-control class within form group..)

**Comment by 8bitDesigner** [comment]
Okay, I think I see what's going on here. Try [this branch](https://github.com/8bitDesigner/ng-form-group/tree/quit-without-inputs) and tell me if that works for your case. I've tried to capture your issue [here as a test case](https://github.com/8bitDesigner/ng-form-group/blob/quit-without-inputs/tests/form-group.coffee#L65-L77) so we can track this. Lemme know if that test case isn't quite testing what you had in mind.

**Comment by aronmgv** [comment]
Yep, that fixed the issue! Thanks

**Comment by 8bitDesigner** [comment]
Okay, great, the latest version ([v1.3.0](https://github.com/8bitDesigner/ng-form-group/releases/tag/v1.3.0)) includes that fix; thanks for catching that!
