### ISSUE TITLE
Not assigning "has-error" or "has-success" to checkbox and other inputs

### ISSUE THREAD

**Issue by aronmgv** [8bitDesigner/ng-form-group#6]
Hey,

Again me.. as you noticed I am trying to implement your module for my forms.. I am using various type of inputs..

Anyways I was testing and it works only for inputs having class `form-control`. So to fix this problem I updated in your module query selector to also consider custom classes. 

So I am using `form-control-others` in order to address elements which cannot have `form-control` class (like checkboxes, selectors, tags and other custom inputs..)
In your code: `querySelectorAll(".form-control")` to `querySelectorAll(".form-control,.form-control-others")`

However I couldnt figure out why for those classes it will never put `has-success` nor `has-error`.. Feedback incons are there but with default black color..

Maybe I am doing something wrong.. since you have screenshots on your page that it works for checkboxes.. I am using standard boostrap 3 approach:

```
<div class="col-md-6">
    <div class="form-group has-feedback">
        <label class="col-md-4 control-label">Deployed:</label>
        <div class="col-md-4">
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="deployed" class="form-control-others" ng-model="networkElement.deployed" required>deployed
                </label>
            </div>
        </div>
    </div>
</div>
```

Thanks in advance! Michal

EDIT: Also useful would be to have a flag somewhere to only apply `has-success`, `has-error` to just a field (keep label on default color..)

**Comment by 8bitDesigner** [comment]
> Anyways I was testing and it works only for inputs having class form-control. So to fix this problem I updated in your module query selector to also consider custom classes.

This is actually a Bootstrap thing; it's adding feedback colors, borders, etc.. to `.form-control` elements inside a `.has-{success,error,warning}` block. You can see [here](https://github.com/twbs/bootstrap/blob/e38f066d8c203c3e032da0ff23cd2d6098ee2dd6/less/forms.less#L427-L436) that the `has-{success,error,warning}` classes include the validation mixin. And [here, in the mixin](https://github.com/twbs/bootstrap/blob/e38f066d8c203c3e032da0ff23cd2d6098ee2dd6/less/mixins/forms.less#L20-L29), you see that it's only applying colors, borders, etc... to the `form-control` elements.

So, your options are to:
1. Just use the `.form-control` class. If this is applying styles you don't want, you'll need to write the CSS to cancel them out.
2. Use your own class, but extend the `form-control-validation` mixin in your Less/Sass file to also apply colors, borders, etc... to your custom class.

> EDIT: Also useful would be to have a flag somewhere to only apply has-success, has-error to just a field (keep label on default color..)

That's [_also_ being done by Bootstrap](https://github.com/twbs/bootstrap/blob/e38f066d8c203c3e032da0ff23cd2d6098ee2dd6/less/mixins/forms.less#L6-L19). If you remove the `.control-label` class from the label element, you should get the behavior you want.
