### ISSUE TITLE
Redundant $digest causes "$digest already in progress" when in child scope

### ISSUE THREAD

**Issue by atruskie** [8bitDesigner/ng-form-group#8]
Hi,

[This line](https://github.com/8bitDesigner/ng-form-group/blob/master/src/form-group.coffee#L14) calls   a `$digest`.

As far as I can see that $digest is redundant and the leftovers of this commit 40dfcfa9c3af6f2feacb3ee9b38e1c231f374f79. As of the current version the `update` method is only ever called from the `$watch` callback (which is guaranteed to be in in a digest already).

This causes an issue when the form is in a child scope. The rootScope can already be in a digest phase and the `$scope.$$phase` check does not work, resulting in the infamous `$digest already in progress` error.

I see two solutions:
- remove [the line](https://github.com/8bitDesigner/ng-form-group/blob/master/src/form-group.coffee#L14) if it is in fact redundant
- or if `update` is used elsewhere, check `$rootScope` for the current `$$phase` as in [$safeApply](https://github.com/yearofmoo/AngularJS-Scope.SafeApply/blob/master/src/Scope.SafeApply.js#L24)
  - this can be done by changing the line in question to  `@$scope.$digest() unless @$scope.$root.$$phase`

**Comment by 8bitDesigner** [comment]
Good catch; I'm ditching the `$$phase` check in [this branch](https://github.com/8bitDesigner/ng-form-group/pull/9/files) and the tests seem to pass. Can you try this out and see if it fixes the issue you're seeing?

**Comment by atruskie** [comment]
:+1: that branch works for all my test cases. Thanks heaps.

**Comment by 8bitDesigner** [comment]
Thank _you_, mate! This is now released in [v1.3.2](https://github.com/8bitDesigner/ng-form-group/releases/tag/v1.3.2)

**Comment by atruskie** [comment]
A quick request: [v1.3.2](https://github.com/8bitDesigner/ng-form-group/releases/tag/v1.3.2) doesn't include the built source so it doesn't work for bower. You you please rebuild and retag?

I'd pull request, but pull-requests don't include tags...

**Comment by 8bitDesigner** [comment]
Aah, gotcha, that's a numpty move on my part. I've unpublished v1.3.2 from npm and Bower, and published v1.3.3 with built source: https://github.com/8bitDesigner/ng-form-group/commit/d093e50e21e159cb1c31355e027bf10171973834
